title: "Mizuta's Playground"
author: "Yukio Mizuta"
email: "yukio.mizuta@protonmail.com"
description: "A minimalist space for exploring Bitcoin, sovereignty, and economic philosophy. Mizuta's Playground offers clear, thoughtful writing on sound money, individual freedom, and the future of global finance."

baseurl: ""
url: "https://playground.mizuta.eu"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
